// <auto-generated />
using Microservices.Application.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BasketServices.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20240311090145_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BasketServices.Application.Entities.CustomerBasket", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CustomerId");

                    b.HasKey("CustomerId")
                        .HasName("Tbl_CustomerBasket_Id");

                    b.ToTable("Tbl_CustomerBasket", (string)null);
                });

            modelBuilder.Entity("Microservices.Application.Entities.BasketItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("BasketItemId");

                    b.Property<string>("CustomerBasketCustomerId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ProductId");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ProductName");

                    b.Property<double>("Quantity")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("Quantity");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Status");

                    b.HasKey("Id")
                        .HasName("Tbl_BasketItem_Pk");

                    b.HasIndex("CustomerBasketCustomerId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Tbl_BasketItem", (string)null);
                });

            modelBuilder.Entity("Microservices.Application.Entities.BasketItem", b =>
                {
                    b.HasOne("BasketServices.Application.Entities.CustomerBasket", null)
                        .WithMany("Items")
                        .HasForeignKey("CustomerBasketCustomerId");
                });

            modelBuilder.Entity("BasketServices.Application.Entities.CustomerBasket", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
